spring.application.name=backend
# DB connection
spring.datasource.url=jdbc:postgresql://localhost:5432/vaidikessence
spring.datasource.username=postgres
spring.datasource.password=password

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger / OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
security.jwt.secret=vaidikessence-super-secret-key-at-least-32-chars
security.jwt.expiration-ms=3600000
